function plotTrialInfo(fn_in_all, fn_out)
    %Plot trial info generated by trialinfo.m
    %
    %Usage:
    %   plotTrialInfo(fn_out_all, fn_out)
    %
    %Input:
    %   fn_in_event = output csv file with recoring info for every day of 2013
    %   fn_out = filename to write .eps plots to
    %
    %Test code:
    %   matpath = './labview/';
    %   fn_out_event = './trialinfo_events.csv';
    %   fn_out_all = './trialinfo_all.csv';
    %   fn_out_eps = './worksheets/02_11_2015/2013_trialinfo';
    %   trialinfo(matpath, fn_out_event, fn_out_all);
    %   plotTrialInfo(fn_out_all, fn_out_eps);

    nD = 364; %number of days of year recorded info for
    nE = 128;
    dates            = zeros(nD, 1);
    cond_secs        = zeros(nD,12);
    electrodeBCIHpos = zeros(nD,nE);
    electrodeBCIVpos = zeros(nD,nE);
    electrodeBCIHvel = zeros(nD,nE);
    electrodeBCIVvel = zeros(nD,nE);
    electrodeBCI2vel = zeros(nD,nE);
    electrodeBCIDual = zeros(nD,nE);
    labels = {'1D Horiz Brain  Position',    '1D Horiz Brain  Velocity',    '1D Horiz Manual Position',    '1D Horiz Manual Velocity',    '1D Vert  Brain  Position',    '1D Vert  Brain  Velocity',    '1D Vert  Manual Position',    '1D Vert  Manual Velocity',    '2D Brain  Velocity',    '2D Manual Position',    '2D Manual Velocity', 'Dual Control'};

    %Read in info into the above matrices
    fh = fopen(fn_in_all, 'r');
    tline = fgetl(fh);
    d = 1;
    while ischar(tline)
        %Split into words
        C = strread(tline,'%s','delimiter',',');
        %Change all strings to numbers
        D = cellfun(@str2num,C,'un',0);
        N = cell2mat(D);
        %Read date
        dates(d) = N(1);
        %Read condition recording times
        cond_secs(d,:) = N(2:13);
        electrodeBCIHpos(d,:) = N(14+0*nE:(14+1*nE-1));
        electrodeBCIVpos(d,:) = N(14+1*nE:(14+2*nE-1));
        electrodeBCIHvel(d,:) = N(14+2*nE:(14+3*nE-1));
        electrodeBCIVvel(d,:) = N(14+3*nE:(14+4*nE-1));
        electrodeBCI2vel(d,:) = N(14+4*nE:(14+5*nE-1));
        electrodeBCIDual(d,:) = N(14+5*nE:(14+6*nE-1));
        d = d + 1;
        tline = fgetl(fh);
    end
    fclose(fh);

    %Compute the change in each matrix
    diffelectrodeBCIHpos = [diff(electrodeBCIHpos); zeros(1, nE)];
    diffelectrodeBCIVpos = [diff(electrodeBCIVpos); zeros(1, nE)];
    diffelectrodeBCIHvel = [diff(electrodeBCIHvel); zeros(1, nE)];
    diffelectrodeBCIVvel = [diff(electrodeBCIVvel); zeros(1, nE)];
    diffelectrodeBCI2vel = [diff(electrodeBCI2vel); zeros(1, nE)];
    diffelectrodeBCIDual = [diff(electrodeBCIDual); zeros(1, nE)];

    xlabeldates = zeros(1,14);
    xlabeldates(1) = datenum('2012-12-01', 'yyyy-mm-dd');
    for idx = 1:12
        if idx < 10
            month = ['0' num2str(idx)];
        else
            month = num2str(idx);
        end
        xlabeldates(idx+1) = datenum(['2013-' month '-01'], 'yyyy-mm-dd');
    end
    xlabeldates(14) = datenum('2013-12-31', 'yyyy-mm-dd');

    %Plot recording condition curves
    clf
    plot(dates, cond_secs(:,1:7)/3600, dates, cond_secs(:,8:12)/3600, '--');
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks');
    xlabel('Date');
    ylabel('Number of recorded hours');
    legend(labels, 'Location', 'bestoutside');
    saveplot(gcf, [fn_out '_rectimes.eps'], 'eps', [9 6]);
    %Plot BCI electrode times for all 6 different condtions
    clf
    imagesc(dates, 1:nE, electrodeBCIHpos'/3600);
    title('BCI 1D horizontal position hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_electrodeBCIHpos.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, electrodeBCIVpos'/3600);
    title('BCI 1D vertical position hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_electrodeBCIVpos.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, electrodeBCIHvel'/3600);
    title('BCI 1D horizontal velocity hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_electrodeBCIHvel.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, electrodeBCIVvel'/3600);
    title('BCI 1D vertical velocity hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_electrodeBCIVvel.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, electrodeBCI2vel'/3600);
    title('BCI 2D velocity hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_electrodeBCI2vel.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, electrodeBCIDual'/3600);
    title('BCI Dual control hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_electrodeBCIdual.eps'], 'eps');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %Plot change in BCI electrode times for all 6 different conditions%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    clf
    imagesc(dates, 1:nE, diffelectrodeBCIHpos'/3600);
    title('BCI 1D horizontal position hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_diffelectrodeBCIHpos.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, diffelectrodeBCIVpos'/3600);
    title('BCI 1D vertical position hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_diffelectrodeBCIVpos.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, diffelectrodeBCIHvel'/3600);
    title('BCI 1D horizontal velocity hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_diffelectrodeBCIHvel.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, diffelectrodeBCIVvel'/3600);
    title('BCI 1D vertical velocity hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_diffelectrodeBCIVvel.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, diffelectrodeBCI2vel'/3600);
    title('BCI 2D velocity hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_diffelectrodeBCI2vel.eps'], 'eps');
    clf
    imagesc(dates, 1:nE, diffelectrodeBCIDual'/3600);
    title('BCI Dual control hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_diffelectrodeBCIdual.eps'], 'eps');

    %Plot combined BCI electrode times for all conditions
    clf
    imagesc(dates, 1:nE, (electrodeBCIHpos+electrodeBCIVpos+electrodeBCIHvel+electrodeBCIVvel+electrodeBCI2vel+electrodeBCIDual)'/3600);
    title('BCI all control hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_electrodeBCIall.eps'], 'eps');
    %Plot change in combined BCI electrode times for all conditions
    clf
    imagesc(dates, 1:nE, (diffelectrodeBCIHpos+diffelectrodeBCIVpos+diffelectrodeBCIHvel+diffelectrodeBCIVvel+diffelectrodeBCI2vel+diffelectrodeBCIDual)'/3600);
    title('BCI all control hours for each electrode')
    set(gca,'XTick',xlabeldates);
    datetick('x','mmm','keepticks', 'keeplimits');
    xlabel('Date');
    ylabel('Electrode');
    colorbar
    saveplot(gcf, [fn_out '_diffelectrodeBCIall.eps'], 'eps');

end