
conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%Get Granger score for BCI units, and relate it to task performance... 
data = fetch(exec(conn, ['SELECT f.unit tounit, f.`nev file`, eg.fromunit, rec.successrate, sum(eg.score) FROM `fits` f '...
'INNER JOIN experiment_tuning et '...
'ON et.`1DBCrecording` = f.`nev file` '...
'INNER JOIN bci_units bciunits '...
'ON f.unit = bciunits.unit AND f.`nev file` = bciunits.ID '...
'INNER JOIN estimates_granger eg '...
'ON eg.id = f.id AND eg.fromunit != f.unit AND EXISTS (SELECT * FROM bci_units bc WHERE bc.ID = f.`nev file` AND eg.fromunit = bc.unit) '...
'INNER JOIN recordings rec '...
'ON rec.`nev file` = f.`nev file` '...
'WHERE modelID = 2 '...
'GROUP BY f.`nev file`']));

gcperfBCI = cell2mat(data.Data(:,4:5));

plot(gcperfBCI(:,1), gcperfBCI(:,2), '.')
xlabel('success rate')
ylabel('sum of granger scores between BC units')
saveplot(gcf, './worksheets/2015_08_08-GrangerVsBCIPerformance/sumgrangerVsPerf.eps')

%How do these values compare to an average GC score?

data = fetch(exec(conn, ['SELECT f.unit tounit, f.`nev file`, eg.fromunit, eg.score '... 
'FROM `fits` f '...
'INNER JOIN experiment_tuning et '...
'ON et.`1DBCrecording` = f.`nev file` '...
'INNER JOIN estimates_granger eg '...
'ON eg.id = f.id AND NOT EXISTS (SELECT * FROM bci_units '...
'bc WHERE bc.ID = f.`nev file` AND (bc.unit = eg.fromunit OR bc.unit = f.unit)) '...
'WHERE modelID = 2']))
gcall = cell2mat(data.Data(:,4));
