function expts = runExperiment(matfile_in, settings, exptname, redo)
	%Fit GLM specified in settings on start and end recordings of all experiments
    %
    %Usage:
    %   expts = runExperiment(matfile_in, settings, exptname)
    %
    %Input:
    %   matpath = filename to csv file output from nevmappings containing all nev and mapping info
    %   settings = structure containing all options for processing and GLM model to fit to data
    %       Generated by setupExperiment()
    %   exptname = basename to save fitted model files for each .nev file
    %   redo = (optional, default = false) will redo everything (rather than continuing where left off)
    %           if needed. (For instance, if a bug is found in a previous run...)
    %
    %Output:
    %	expts = structure array listing experiment details:
    %		.nevfile_start = nevfile before
    %		.nevfile_end = nevfile after
    %		.matfile_start = matfile before
    %		.matfile_end = matfile after
    %		.cond_secs = [1xnC] array listing number of seconds of trials under each condition 
    %		.events = details about all the events that come in between start and end, including BCI units used
    %			between start and end recording -- what we'll be fitting a model to.
    %       .settings = settings provided by setupExperiment
    %       .modelstart = fit GLM to start recording
    %       .modelend = fit GLM to end recording
    %
    %Test code:
    %   matfile_in = './expts/2dmanualpos_1day.mat';
    %   settings = setupExperiment('sprc_def');
    %   exptname = '2dmanualpos_sprc_def';
    %   expts = runExperiment(matfile_in, settings, exptname);

    if (nargin < 4) redo = false; end
	load(matfile_in);
	nexpts = length(expts);

	%Iterate over expts structure
	for idx = 1:nexpts
        expt = expts(idx);
        %Determine if models have already been fit and saved in ./expts/
        nev_start = expt.nevfile_start;
        nev_end = expt.nevfile_end;
        mat_start = expt.matfile_start;
        mat_end = expt.matfile_end;
        fn_start = ['./expts/' exptname '_' nev_start(1:end-4) '.mat'];
        fn_end = ['./expts/' exptname '_' nev_end(1:end-4) '.mat'];
        %Process starting recording, unless it already has been during a previous experiment
        if (exist(fn_start, 'file') == 2) & ~redo
            display([fn_start ' already fit. Continuing'])
            load(fn_start);
            %Check if structure has unitnames, if not add them
            if ~isfield(model, 'unitnames')
                display(['Model ' fn_start ' does not contain unit names, adding.'])
                processed = settings.process([settings.nevfiledir expt.nevfile_start], [settings.matfiledir expt.matfile_start]);
                processed_mua = combine_mua(processed);
                model.unitnames = processed_mua.unitnames;
            end
            save(fn_start, 'model');
        else
            display([fn_start ' not fit. Fitting GLM to ' expt.nevfile_start])
            %If not, preprocess data
            try 
                processed = settings.process([settings.nevfiledir expt.nevfile_start], [settings.matfiledir expt.matfile_start]);
                %Combine data to same electrode
                processed_mua = combine_mua(processed);
                %Truncate to 'duration' seconds of recording
                processed_mua = truncate_recording(processed_mua, settings.duration);
                %Create filters
                data = settings.filters(processed_mua);
                %Fit model
                model = settings.fit(data, settings.const);
                model.unitnames = processed_mua.unitnames;
                model.na = false;
            catch err
                %Write a blank model to file
                if strcmp(err.identifier, 'BCIGLM:filters_sprc_pos_target:noTargetInformation')
                    display(['Recording ' expt.nevfile_end ' contains no trials. Inappropriate model for this file. Skipping.'])
                    model.na = true;
                    model.unitnames = {};
                elseif strcmp(err.identifier, 'preprocess:labviewrecording:rareSampleRate')
                    display('Sample rate rare. Will not process this file. Continuing.')
                    model.na = true;
                    model.unitnames = {};
                else
                    throw(err)
                end
            end
            %Save fit model as ./expts/exptname_nevfile.mat
            save(fn_start, 'model');            
        end
        %Add to .modelstart
        expt.modelstart = model;
        %Do the same for the ending recording
        if (exist(fn_end, 'file') == 2) & ~redo
            display([fn_end ' already fit. Continuing'])
            load(fn_end);
            %Check if structure has unitnames, if not add them
            if ~isfield(model, 'unitnames')
                display(['Model ' fn_end ' does not contain unit names, adding.'])
                processed = settings.process([settings.nevfiledir expt.nevfile_start], [settings.matfiledir expt.matfile_start]);
                processed_mua = combine_mua(processed);
                model.unitnames = processed_mua.unitnames;
            end
            save(fn_end, 'model');
        else
            display([fn_end ' not fit. Fitting GLM'])
            try
                %If hasn't been processed, do it
                processed = settings.process([settings.nevfiledir expt.nevfile_end], [settings.matfiledir expt.matfile_end]);
                %Combine data from same electrode
                processed_mua = combine_mua(processed);
                %Truncate to 'duration' seconds of recording
                processed_mua = truncate_recording(processed_mua, settings.duration);
                %Create filters
                data = settings.filters(processed_mua);
                %Fit model
                model = settings.fit(data, settings.const);
                model.unitnames = processed_mua.unitnames;
                model.na = false;
            catch err
                %Write a blank model to file
                if strcmp(err.identifier, 'BCIGLM:filters_sprc_pos_target:noTargetInformation')
                    display(['Recording ' expt.nevfile_end ' contains no trials. Inappropriate model for this file. Skipping MLE fit.'])
                    model.na = true;
                    model.unitnames = {};
                elseif strcmp(err.identifier, 'preprocess:labviewrecording:rareSampleRate')
                    display('Sample rate rare. Will not process this file. Continuing.')
                    model.na = true;
                    model.unitnames = {};
                else
                    display(err.identifier);
                    throw(err)
                end
            end
            %Save fit model as ./expts/exptname_nevfile.mat
            save(fn_end, 'model');            
        end
        %Add to .modelend
        expt.modelend = model;
        %Return
        fitexpts(idx) = expt;
    end
    expts = fitexpts;
end



