conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

causaldensity = exec(conn, ['SELECT mc1.causaldensity mc1cd, bc.causaldensity bccd, mc2.causaldensity mc2cd' ...
' FROM'...
' analysis_mvgc mc1 '...
' INNER JOIN analyses f1'...
' ON f1.id = mc1.id '...
' INNER JOIN experiment_tuning al '...
' ON al.experiment_id = f1.experiment_id'...
' INNER JOIN analyses f2'...
' ON f2.`nev file` = al.`1DBCrecording` AND f2.modelID = 13'...
' INNER JOIN analysis_mvgc bc '...
' ON bc.id = f2.id '...
' INNER JOIN analyses f3'...
' ON f3.`nev file` = al.`manualrecordingafter` AND f3.modelID = 13'...
' INNER JOIN analysis_mvgc mc2'...
' ON mc2.id = f3.id'...
' WHERE f1.modelID = 13'])
causaldensity = fetch(causaldensity)
causaldensity = cell2mat(causaldensity.Data(:));

clf
subplot(1,3,1)
hist(causaldensity(:,1))
xlim([0 1])
set(get(gca,'child'),'FaceColor',[0 0.5 0.5],'EdgeColor','w');
subplot(1,3,2)
hist(causaldensity(:,2))
xlim([0 1])
set(get(gca,'child'),'FaceColor',[0.5 0 0.5],'EdgeColor','w');
subplot(1,3,3)
hist(causaldensity(:,3))
xlim([0 1])
set(get(gca,'child'),'FaceColor',[0.5 0.5 0],'EdgeColor','w');




granger = fetch(exec(conn, ['SELECT mc1.score mc1score, bc.score bcscore, mc2.score mc2score, f1.`nev file` mc1nev, mc1.fromunit'...
' FROM'...
' estimates_granger mc1 '...
' INNER JOIN fits f1'...
' ON f1.id = mc1.id '...
' INNER JOIN experiment_tuning al '...
' ON al.`manualrecording` = f1.`nev file`'...
' INNER JOIN fits f2'...
' ON f2.`nev file` = al.`1DBCrecording` AND f2.modelID = 13'...
' INNER JOIN estimates_granger bc '...
' ON bc.id = f2.id AND mc1.fromunit = bc.fromunit '...
' INNER JOIN fits f3'...
' ON f3.`nev file` = al.`manualrecordingafter` AND f3.modelID = 13'...
' INNER JOIN estimates_granger mc2'...
' ON mc2.id = f3.id AND mc2.fromunit = mc1.fromunit'...
' WHERE f1.modelID = 13']))
granger = cell2mat(granger.Data(:,1:3));

clf
subplot(1,3,1)
hist(log10(granger(:,1)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0 0.5 0.5],'EdgeColor','w');
subplot(1,3,2)
hist(log10(granger(:,2)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0.5 0 0.5],'EdgeColor','w');
subplot(1,3,3)
hist(log10(granger(:,3)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0.5 0.5 0],'EdgeColor','w');


grangerbci = fetch(exec(conn, ['SELECT mc1.score mc1score, bc.score bcscore, mc2.score mc2score, bci.unit IS NOT NULL bciunit, f1.`nev file` mc1nev, mc1.fromunit'...
' FROM'...
' estimates_granger mc1 '...
' INNER JOIN fits f1'...
' ON f1.id = mc1.id '...
' INNER JOIN experiment_tuning al '...
' ON al.`manualrecording` = f1.`nev file`'...
' INNER JOIN fits f2'...
' ON f2.`nev file` = al.`1DBCrecording` AND f2.modelID = 13'...
' INNER JOIN estimates_granger bc '...
' ON bc.id = f2.id AND mc1.fromunit = bc.fromunit '...
' INNER JOIN fits f3'...
' ON f3.`nev file` = al.`manualrecordingafter` AND f3.modelID = 13'...
' INNER JOIN estimates_granger mc2'...
' ON mc2.id = f3.id AND mc2.fromunit = mc1.fromunit'...
' LEFT JOIN bci_units bci'...
' ON bci.ID = al.`1DBCrecording` AND bci.unit = mc1.fromunit'...
' WHERE f1.modelID = 13']))
grangerbci = cell2mat(grangerbci.Data(:,1:4))

figure
bciidx = grangerbci(:,4)==1;
subplot(1,3,1)
hist(log10(grangerbci(bciidx,1)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0 0.5 0.5],'EdgeColor','w');
subplot(1,3,2)
hist(log10(grangerbci(bciidx,2)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0.5 0 0.5],'EdgeColor','w');
subplot(1,3,3)
hist(log10(grangerbci(bciidx,3)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0.5 0.5 0],'EdgeColor','w');
title('Granger brain control units')

figure
subplot(1,3,1)
hist(log10(grangerbci(~bciidx,1)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0 0.5 0.5],'EdgeColor','w');
subplot(1,3,2)
hist(log10(grangerbci(~bciidx,2)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0.5 0 0.5],'EdgeColor','w');
subplot(1,3,3)
hist(log10(grangerbci(~bciidx,3)))
xlim([-5 0])
set(get(gca,'child'),'FaceColor',[0.5 0.5 0],'EdgeColor','w');
title('Granger non- brain control units')


%For specific recordings...
grangerbci = fetch(exec(conn, ['SELECT mc1.score mc1score, bc.score bcscore, mc2.score mc2score, bci.unit IS NOT NULL bciunit, f1.`nev file` mc1nev, mc1.fromunit'...
' FROM'...
' estimates_granger mc1 '...
' INNER JOIN fits f1'...
' ON f1.id = mc1.id '...
' INNER JOIN experiment_tuning al '...
' ON al.`manualrecording` = f1.`nev file`'...
' INNER JOIN fits f2'...
' ON f2.`nev file` = al.`1DBCrecording` AND f2.modelID = 13'...
' INNER JOIN estimates_granger bc '...
' ON bc.id = f2.id AND mc1.fromunit = bc.fromunit '...
' INNER JOIN fits f3'...
' ON f3.`nev file` = al.`manualrecordingafter` AND f3.modelID = 13'...
' INNER JOIN estimates_granger mc2'...
' ON mc2.id = f3.id AND mc2.fromunit = mc1.fromunit'...
' LEFT JOIN bci_units bci'...
' ON bci.ID = al.`1DBCrecording` AND bci.unit = mc1.fromunit'...
' WHERE f1.modelID = 13 AND f1.`nev file` = "20130920SpankyUtah001.nev"']))
grangerbci = cell2mat(grangerbci.Data(:,1:4))