conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%Pull out the SE of the angle in MC, and use that to quantify when it changes significantly

%Tuning angles, BCI units (velocity)
bci_data = fetch(exec(conn, ['SELECT ep1FE.value, ep1RU.value, ep2FE.value, ep2RU.value, ep3FE.value, ep3RU.value, ep5FE.value, ep5RU.value, ep1FE.SE, ep1RU.SE, ep2FE.SE, ep2RU.SE, ep3FE.SE, ep3RU.SE, ep5FE.SE, ep5RU.SE, et1.`tuning_type`, rec1.`successrate`, rec2.`successrate`, '...
' IF(EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et1.`1DBCrecording` AND bci.unit = flin1.unit), '...
' 1, 0), flin1.`nev file` FROM '...
'`experiment_tuning` et1 '...
'INNER JOIN `fits` flin1 '...
'ON flin1.`nev file` = et1.`manualrecording` '...
'INNER JOIN `fits_linear` fl1 '...
'ON flin1.id = fl1.id '...
'INNER JOIN `estimates_parameters` ep1FE '...
'ON flin1.id = ep1FE.id AND ep1FE.label = "FE vel" '...
'INNER JOIN `estimates_parameters` ep1RU '...
'ON flin1.id = ep1RU.id AND ep1RU.label = "RU vel"  '...
'INNER JOIN `fits` flin2 '...
'ON flin2.`nev file` = et1.`1DBCrecording`'...
'INNER JOIN `estimates_parameters` ep2FE '...
'ON flin2.id = ep2FE.id AND ep2FE.label = "FE vel"  '...
'INNER JOIN `estimates_parameters` ep2RU '...
'ON flin2.id = ep2RU.id AND ep2RU.label = "RU vel"  '...
'INNER JOIN `fits` flin3 '...
'ON flin3.`nev file` = et1.`manualrecordingafter`'...
'INNER JOIN `fits_linear` fl3 '...
'ON flin3.id = fl3.id '...
'INNER JOIN `estimates_parameters` ep3FE '...
'ON flin3.id = ep3FE.id AND ep3FE.label = "FE vel"  '...
'INNER JOIN `estimates_parameters` ep3RU '...
'ON flin3.id = ep3RU.id AND ep3RU.label = "RU vel"  '...
'INNER JOIN `fits` flin5 '...
'ON flin5.`nev file` = et1.`dualrecording`'...
'INNER JOIN `recordings` rec1 '...
'ON rec1.`nev file` = et1.`1DBCrecording` '...
'INNER JOIN `estimates_parameters` ep5FE '...
'ON flin5.id = ep5FE.id AND ep5FE.label = "FE vel"  '...
'INNER JOIN `estimates_parameters` ep5RU '...
'ON flin5.id = ep5RU.id AND ep5RU.label = "RU vel"  '...
'INNER JOIN `recordings` rec2 '...
'ON rec2.`nev file` = et1.`dualrecording` '...
'WHERE flin1.modelID = 30 AND flin2.modelID = 30 AND flin3.modelID = 30 AND flin5.modelID = 30 ' ...
'AND flin1.unit = flin2.unit AND flin2.unit = flin3.unit AND flin2.unit = flin5.unit '...
'AND fl1.r2 > .01 AND fl3.r2 > .01']));

all_val = cell2mat(bci_data.Data(:,1:8));
all_SE = cell2mat(bci_data.Data(:,9:16));
bcituningtype = cell2mat(bci_data.Data(:,17));
bciunit = cell2mat(bci_data.Data(:,18));

rot = (bcituningtype == 1 | bcituningtype == 3| bcituningtype == 4);
bci = (bciunit == 1) & rot;
nonbci = (bciunit == 0) & rot;

%1 = mc1 
%2 = bc
%3 = mc2 
%4 = dc 

BCFEz = abs(all_val(:,1)-all_val(:,3))./all_SE(:,1);
BCRUz = abs(all_val(:,2)-all_val(:,4))./all_SE(:,2);
MC2FEz = abs(all_val(:,1)-all_val(:,5))./all_SE(:,1);
MC2RUz = abs(all_val(:,2)-all_val(:,6))./all_SE(:,2);
DCFEz = abs(all_val(:,1)-all_val(:,7))./all_SE(:,1);
DCRUz = abs(all_val(:,2)-all_val(:,8))./all_SE(:,2);

sum(BCFEz > 3)
sum(BCRUz > 3)
sum(MC2FEz > 3)
sum(MC2RUz > 3)
sum(DCFEz > 3)
sum(DCRUz > 3)

%Forget about computing the angle... just compute the SE of the parameter and see when if changes
%at a 2-sigma level
