conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');
grangerMCBC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`1DBCrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31']));
grangerMC = cell2mat(grangerMCBC.Data(:,5));
grangerBC = cell2mat(grangerMCBC.Data(:,6));
tuningtype = cell2mat(grangerMCBC.Data(:,9));

devconstMC = cell2mat(grangerMCBC.Data(:,7));
devconstBC = cell2mat(grangerMCBC.Data(:,8));
normgrangerMC = 100*grangerMC./devconstMC;
normgrangerBC = 100*grangerBC./devconstBC;

unrot1 = tuningtype == 5;
rot1 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned1 = tuningtype == 4;

grangerMCMC2 = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`manualrecordingafter` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31'])); 
grangerMCb = cell2mat(grangerMCMC2.Data(:,5));
grangerMC2 = cell2mat(grangerMCMC2.Data(:,6));
devconstMCb = cell2mat(grangerMCMC2.Data(:,7));
devconstMC2 = cell2mat(grangerMCMC2.Data(:,8));
tuningtype = cell2mat(grangerMCMC2.Data(:,9));
normgrangerMCb = grangerMCb./devconstMCb;
normgrangerMC2 = grangerMC2./devconstMC2;

unrot2 = tuningtype == 5;
rot2 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned2 = tuningtype == 4;

grangerMCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id'...
' AND fconstBC.modelID = 31 AND fconstMC.modelID = 31']));
grangerMCc = cell2mat(grangerMCDC.Data(:,5));
grangerDC = cell2mat(grangerMCDC.Data(:,6));
devconstMCc = cell2mat(grangerMCDC.Data(:,7));
devconstDC = cell2mat(grangerMCDC.Data(:,8));
tuningtype = cell2mat(grangerMCDC.Data(:,9));
normgrangerMCc = grangerMCc./devconstMCc;
normgrangerDC = grangerDC./devconstDC;

unrot3 = tuningtype == 5;
rot3 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned3 = tuningtype == 4;

grangerBCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`1DBCrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31']));
grangerBCb = cell2mat(grangerBCDC.Data(:,5));
grangerDC = cell2mat(grangerBCDC.Data(:,6));
devconstBCb = cell2mat(grangerBCDC.Data(:,7));
devconstDC = cell2mat(grangerBCDC.Data(:,8));
tuningtype = cell2mat(grangerBCDC.Data(:,9));

unrot4 = tuningtype == 5;
rot4 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned4 = tuningtype == 4;

normgrangerBCb = grangerBCb./devconstBCb;
normgrangerDC = grangerDC./devconstDC;

corrs(1) = corr(grangerMC, grangerBC);
corrs(2) = corr(grangerMCb, grangerMC2);
corrs(3) = corr(grangerMCc, grangerDC);
corrs(4) = corr(grangerBCb, grangerDC);

corrsrotated(1) = corr(grangerMC(rot1), grangerBC(rot1));
corrsrotated(2) = corr(grangerMCb(rot2), grangerMC2(rot2));
corrsrotated(3) = corr(grangerMCc(rot3), grangerDC(rot3));
corrsrotated(4) = corr(grangerBCb(rot4), grangerDC(rot4));

corrsunrotated(1) = corr(grangerMC(unrot1), grangerBC(unrot1));
corrsunrotated(2) = corr(grangerMCb(unrot2), grangerMC2(unrot2));
corrsunrotated(3) = corr(grangerMCc(unrot3), grangerDC(unrot3));
corrsunrotated(4) = corr(grangerBCb(unrot4), grangerDC(unrot4));

clf
subplot(2,2,1)
plot(grangerMC, grangerBC, '.')
xlabel('MC')
ylabel('BC')
title(['corr rotated: ' num2str(corrsrotated(1)) ' corr unrotated: ' num2str(corrsunrotated(1))])
subplot(2,2,2)
plot(grangerMCb, grangerMC2, '.')
xlabel('MC1')
ylabel('MC2')
title(['corr rotated: ' num2str(corrsrotated(2)) ' corr unrotated: ' num2str(corrsunrotated(2))])
subplot(2,2,3)
plot(grangerMCc, grangerDC, '.')
xlabel('MC')
ylabel('DC')
title(['corr rotated: ' num2str(corrsrotated(3)) ' corr unrotated: ' num2str(corrsunrotated(3))])
subplot(2,2,4)
plot(grangerBCb, grangerDC, '.')
xlabel('BC')
ylabel('DC')
title(['corr rotated: ' num2str(corrsrotated(4)) ' corr unrotated: ' num2str(corrsunrotated(4))])
saveplot(gcf, './worksheets/2015_11_03-bcireportplots/grangercondcompare.eps')

normcorrs(1) = corr(normgrangerMC, normgrangerBC);
normcorrs(2) = corr(normgrangerMCb, normgrangerMC2);
normcorrs(3) = corr(normgrangerMCc, normgrangerDC);
normcorrs(4) = corr(normgrangerBCb, normgrangerDC);

normcorrsrotated(1) = corr(normgrangerMC(rot1), normgrangerBC(rot1));
normcorrsrotated(2) = corr(normgrangerMCb(rot2), normgrangerMC2(rot2));
normcorrsrotated(3) = corr(normgrangerMCc(rot3), normgrangerDC(rot3));
normcorrsrotated(4) = corr(normgrangerBCb(rot4), normgrangerDC(rot4));

normcorrsunrotated(1) = corr(normgrangerMC(unrot1), normgrangerBC(unrot1));
normcorrsunrotated(2) = corr(normgrangerMCb(unrot2), normgrangerMC2(unrot2));
normcorrsunrotated(3) = corr(normgrangerMCc(unrot3), normgrangerDC(unrot3));
normcorrsunrotated(4) = corr(normgrangerBCb(unrot4), normgrangerDC(unrot4));

clf
subplot(2,2,1)
plot(normgrangerMC, normgrangerBC, '.')
xlabel('MC')
ylabel('BC')
title(['Corr: ' num2str(normcorrs(1))])
subplot(2,2,2)
plot(normgrangerMCb, normgrangerMC2, '.')
xlabel('MC1')
ylabel('MC2')
title(['Corr: ' num2str(normcorrs(2))])
subplot(2,2,3)
plot(normgrangerMCc, normgrangerDC, '.')
xlabel('MC')
ylabel('DC')
title(['Corr: ' num2str(normcorrs(3))])
subplot(2,2,4)
plot(normgrangerBCb, normgrangerDC, '.')
xlabel('BC')
ylabel('DC')
title(['Corr: ' num2str(normcorrs(4))])
saveplot(gcf, './worksheets/2015_11_03-bcireportplots/normgrangercondcompare.eps')


%For individual recordings
mcrec = fetch(exec(conn, ['SELECT et.`manualrecording`, et.`1DBCrecording` FROM experiment_tuning et']));
mcrec = mcrec.Data;
nR = size(mcrec,1);

corrsMCBC = [];
corrsMCMC2 = [];
corrsMCDC = [];
corrsBCDC = [];
tuningtype = [];
performanceBC = [];
performanceDC = [];
performanceBCDC = [];

for idx = 1:nR
	mcfile = mcrec{idx,1};
	bcfile = mcrec{idx,2};
	grangerMCBC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, et.`tuning_type`, rec.successrate FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fMC '...
	'ON et.`manualrecording` = fMC.`nev file` '...
	'INNER JOIN `estimates_granger` egMC '...
	'ON egMC.`id` = fMC.`id` '...
	'INNER JOIN `fits` fBC '...
	'ON et.`1DBCrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `recordings` rec '...
	'ON rec.`nev file` = et.`1DBCrecording` '...
	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' mcfile '"']));
	if length(grangerMCBC.Data) > 1
		grangerMC = cell2mat(grangerMCBC.Data(:,5));
		grangerBC = cell2mat(grangerMCBC.Data(:,6));
		corrsMCBC(idx) = corr(grangerMC, grangerBC);
		tuningtype(idx) = cell2mat(grangerMCBC.Data(1,7));
		performanceBC(idx) = cell2mat(grangerMCBC.Data(1,8));
	end
	grangerMCMC2 = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, et.`tuning_type`, rec.successrate FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fMC '...
	'ON et.`manualrecording` = fMC.`nev file` '...
	'INNER JOIN `estimates_granger` egMC '...
	'ON egMC.`id` = fMC.`id` '...
	'INNER JOIN `fits` fBC '...
	'ON et.`manualrecordingafter` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `recordings` rec '...
	'ON rec.`nev file` = et.`1DBCrecording` '...
	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' mcfile '"']));
	if length(grangerMCMC2.Data) > 1
		grangerMCb = cell2mat(grangerMCMC2.Data(:,5));
		grangerMC2 = cell2mat(grangerMCMC2.Data(:,6));
		corrsMCMC2(idx) = corr(grangerMCb, grangerMC2);
		tuningtype(idx) = cell2mat(grangerMCMC2.Data(1,7));
	end
	
	grangerMCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, et.`tuning_type`, rec.successrate FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fMC '...
	'ON et.`manualrecording` = fMC.`nev file` '...
	'INNER JOIN `estimates_granger` egMC '...
	'ON egMC.`id` = fMC.`id` '...
	'INNER JOIN `fits` fBC '...
	'ON et.`dualrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `recordings` rec '...
	'ON rec.`nev file` = et.`dualrecording` '...
	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' mcfile '"']));
	if length(grangerMCDC.Data) > 1
		grangerMCc = cell2mat(grangerMCDC.Data(:,5));
		grangerDC = cell2mat(grangerMCDC.Data(:,6));
		corrsMCDC(idx) = corr(grangerMCc, grangerDC);
		tuningtype(idx) = cell2mat(grangerMCDC.Data(1,7));
		performanceDC(idx) = cell2mat(grangerMCDC.Data(1,8));
	end
	grangerBCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
	' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, et.`tuning_type`, rec1.successrate, rec2.successrate FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fMC '...
	'ON et.`1DBCrecording` = fMC.`nev file` '...
	'INNER JOIN `estimates_granger` egMC '...
	'ON egMC.`id` = fMC.`id` '...
	'INNER JOIN `fits` fBC '...
	'ON et.`dualrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `recordings` rec1 '...
	'ON rec1.`nev file` = et.`1DBCrecording` '...
	'INNER JOIN `recordings` rec2 '...
	'ON rec2.`nev file` = et.`dualrecording` '...
	'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id AND fMC.`nev file` = "' bcfile '"']));
	if length(grangerBCDC.Data) > 1
		grangerBCb = cell2mat(grangerBCDC.Data(:,5));
		grangerDC = cell2mat(grangerBCDC.Data(:,6));
		corrsBCDC(idx) = corr(grangerBCb, grangerDC);
		tuningtype(idx) = cell2mat(grangerBCDC.Data(1,7));
		performanceBCDC(idx,1:2) = cell2mat(grangerBCDC.Data(1,8:9));
	end
end

plot(corrsMCBC, performanceBC, '.')
saveplot(gcf, './worksheets/2015_11_03-bcireportplots/grangerMCBC_performance.eps')

plot(corrsMCDC, performanceDC, '.')
saveplot(gcf, './worksheets/2015_11_03-bcireportplots/grangerMCDC_performance.eps')

plot(corrsBCDC, performanceBCDC, '.')

plot(performanceBCDC(:,1), performanceBCDC(:,2))

rot = tuningtype < 5;
unrot = tuningtype == 5;

subplot(3,4,1)
hist(corrsMCBC(corrsMCBC~=0))
xlabel('Corr MCBC')
xlim([0 1])
subplot(3,4,2)
hist(corrsMCMC2(corrsMCMC2~=0))
xlabel('Corr MCMC')
xlim([0 1])
subplot(3,4,3)
hist(corrsMCDC(corrsMCDC~=0))
xlabel('Corr MCDC')
xlim([0 1])
subplot(3,4,4)
hist(corrsBCDC(corrsBCDC~=0))
xlabel('Corr BCDC')
xlim([0 1])

subplot(3,4,5)
hist(corrsMCBC(corrsMCBC~=0 & unrot))
xlabel('Unrotated Corr MCBC')
xlim([0 1])
subplot(3,4,6)
hist(corrsMCMC2(corrsMCMC2~=0 & unrot))
xlabel('Unrotated Corr MCMC')
xlim([0 1])
subplot(3,4,7)
hist(corrsMCDC(corrsMCDC~=0 & unrot))
xlabel('Unrotated Corr MCDC')
xlim([0 1])
subplot(3,4,8)
hist(corrsBCDC(corrsBCDC~=0 & unrot))
xlabel('Unrotated Corr BCDC')
xlim([0 1])

subplot(3,4,9)
hist(corrsMCBC(corrsMCBC~=0 & rot))
xlabel('Rotated Corr MCBC')
xlim([0 1])
subplot(3,4,10)
hist(corrsMCMC2(corrsMCMC2~=0 & rot))
xlabel('Rotated Corr MCMC')
xlim([0 1])
subplot(3,4,11)
hist(corrsMCDC(corrsMCDC~=0 & rot))
xlabel('Rotated Corr MCDC')
xlim([0 1])
subplot(3,4,12)
hist(corrsBCDC(corrsBCDC~=0 & rot))
xlabel('Rotated Corr BCDC')
xlim([0 1])
saveplot(gcf, './worksheets/2015_11_03-bcireportplots/grangercondcompare_perfile.eps', 'eps', [10 10])

