conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%%%%%%%%%%%%%
%To BC units%
%%%%%%%%%%%%%

grangerMCBC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`1DBCrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`1DBCrecording` AND bci.unit = fMC.unit)']));
grangerMC = cell2mat(grangerMCBC.Data(:,5));
grangerBC = cell2mat(grangerMCBC.Data(:,6));
tuningtype = cell2mat(grangerMCBC.Data(:,9));
cc1 = ones(size(tuningtype));
cc1(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc1(tuningtype == 5) = 3;

devconstMC = cell2mat(grangerMCBC.Data(:,7));
devconstBC = cell2mat(grangerMCBC.Data(:,8));
normgrangerMC = 100*grangerMC./devconstMC;
normgrangerBC = 100*grangerBC./devconstBC;

unrot1 = tuningtype == 5;
rot1 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned1 = tuningtype == 4;

grangerMCMC2 = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`manualrecordingafter` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '... 
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`1DBCrecording` AND bci.unit = fMC.unit)']));
grangerMCb = cell2mat(grangerMCMC2.Data(:,5));
grangerMC2 = cell2mat(grangerMCMC2.Data(:,6));
tuningtype = cell2mat(grangerMCMC2.Data(:,9));
cc2 = ones(size(tuningtype));
cc2(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc2(tuningtype == 5) = 3;

unrot2 = tuningtype == 5;
rot2 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned2 = tuningtype == 4;

grangerMCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id'...
' AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`dualrecording` AND bci.unit = fMC.unit)']));
grangerMCc = cell2mat(grangerMCDC.Data(:,5));
grangerDC = cell2mat(grangerMCDC.Data(:,6));
tuningtype = cell2mat(grangerMCDC.Data(:,9));
cc3 = ones(size(tuningtype));
cc3(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc3(tuningtype == 5) = 3;

unrot3 = tuningtype == 5;
rot3 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned3 = tuningtype == 4;

grangerBCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`1DBCrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`1DBCrecording` AND bci.unit = fMC.unit)']));
grangerBCb = cell2mat(grangerBCDC.Data(:,5));
grangerDCb = cell2mat(grangerBCDC.Data(:,6));
tuningtype = cell2mat(grangerBCDC.Data(:,9));
cc4 = ones(size(tuningtype));
cc4(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc4(tuningtype == 5) = 3;

unrot4 = tuningtype == 5;
rot4 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned4 = tuningtype == 4;

corrs(1) = corr(grangerMC, grangerBC)
corrs(2) = corr(grangerMCb, grangerMC2)
corrs(3) = corr(grangerMCc, grangerDC)
corrs(4) = corr(grangerBCb, grangerDCb)

corrsunrotated(1) = corr(grangerMC(unrot1), grangerBC(unrot1))
corrsunrotated(2) = corr(grangerMCb(unrot2), grangerMC2(unrot2))
corrsunrotated(3) = corr(grangerMCc(unrot3), grangerDC(unrot3))
corrsunrotated(4) = corr(grangerBCb(unrot4), grangerDCb(unrot4))

corrsrotated(1) = corr(grangerMC(rot1), grangerBC(rot1))
corrsrotated(2) = corr(grangerMCb(rot2), grangerMC2(rot2))
corrsrotated(3) = corr(grangerMCc(rot3), grangerDC(rot3))
corrsrotated(4) = corr(grangerBCb(rot4), grangerDCb(rot4))

clf
colors = [0 0 0; 1 0 0; 0 0 1];
colormap(colors);
subplot(2,2,1)
scatter(grangerMC, grangerBC, [], cc1)
xlabel('MC')
ylabel('BC')
title(['corr: ' num2str(corrs(1)) ' corr rotated: ' num2str(corrsrotated(1)) ' corr unrotated: ' num2str(corrsunrotated(1))])
subplot(2,2,2)
scatter(grangerMCb, grangerMC2, [], cc2)
xlabel('MC1')
ylabel('MC2')
title(['corr: ' num2str(corrs(2)) ' corr rotated: ' num2str(corrsrotated(2)) ' corr unrotated: ' num2str(corrsunrotated(2))])
subplot(2,2,3)
scatter(grangerMCc, grangerDC, [], cc3)
xlabel('MC')
ylabel('DC')
title(['corr: ' num2str(corrs(3)) ' corr rotated: ' num2str(corrsrotated(3)) ' corr unrotated: ' num2str(corrsunrotated(3))])
subplot(2,2,4)
scatter(grangerBCb, grangerDCb, [], cc4)
xlabel('BC')
ylabel('DC')
title(['corr: ' num2str(corrs(4)) ' corr rotated: ' num2str(corrsrotated(4)) ' corr unrotated: ' num2str(corrsunrotated(4))])
saveplot(gcf, './worksheets/2015_11_03-bcireportplots/grangercondcompareToBCunits.eps', 'eps', [10 10])


%%%%%%%%%%%%%
%To BC units%
%%%%%%%%%%%%%


grangerMCBC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`1DBCrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`1DBCrecording` AND bci.unit = egMC.fromunit)']));
grangerMC = cell2mat(grangerMCBC.Data(:,5));
grangerBC = cell2mat(grangerMCBC.Data(:,6));
tuningtype = cell2mat(grangerMCBC.Data(:,9));
cc1 = ones(size(tuningtype));
cc1(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc1(tuningtype == 5) = 3;

devconstMC = cell2mat(grangerMCBC.Data(:,7));
devconstBC = cell2mat(grangerMCBC.Data(:,8));
normgrangerMC = 100*grangerMC./devconstMC;
normgrangerBC = 100*grangerBC./devconstBC;

unrot1 = tuningtype == 5;
rot1 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned1 = tuningtype == 4;

grangerMCMC2 = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`manualrecordingafter` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '... 
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`1DBCrecording` AND bci.unit = egMC.fromunit)']));
grangerMCb = cell2mat(grangerMCMC2.Data(:,5));
grangerMC2 = cell2mat(grangerMCMC2.Data(:,6));
tuningtype = cell2mat(grangerMCMC2.Data(:,9));
cc2 = ones(size(tuningtype));
cc2(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc2(tuningtype == 5) = 3;

unrot2 = tuningtype == 5;
rot2 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned2 = tuningtype == 4;

grangerMCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id'...
' AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`dualrecording` AND bci.unit = egMC.fromunit)']));
grangerMCc = cell2mat(grangerMCDC.Data(:,5));
grangerDC = cell2mat(grangerMCDC.Data(:,6));
tuningtype = cell2mat(grangerMCDC.Data(:,9));
cc3 = ones(size(tuningtype));
cc3(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc3(tuningtype == 5) = 3;

unrot3 = tuningtype == 5;
rot3 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned3 = tuningtype == 4;

grangerBCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`1DBCrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`1DBCrecording` AND bci.unit = egMC.fromunit)']));
grangerBCb = cell2mat(grangerBCDC.Data(:,5));
grangerDCb = cell2mat(grangerBCDC.Data(:,6));
tuningtype = cell2mat(grangerBCDC.Data(:,9));
cc4 = ones(size(tuningtype));
cc4(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc4(tuningtype == 5) = 3;

unrot4 = tuningtype == 5;
rot4 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned4 = tuningtype == 4;

corrs(1) = corr(grangerMC, grangerBC)
corrs(2) = corr(grangerMCb, grangerMC2)
corrs(3) = corr(grangerMCc, grangerDC)
corrs(4) = corr(grangerBCb, grangerDCb)

corrsunrotated(1) = corr(grangerMC(unrot1), grangerBC(unrot1))
corrsunrotated(2) = corr(grangerMCb(unrot2), grangerMC2(unrot2))
corrsunrotated(3) = corr(grangerMCc(unrot3), grangerDC(unrot3))
corrsunrotated(4) = corr(grangerBCb(unrot4), grangerDCb(unrot4))

corrsrotated(1) = corr(grangerMC(rot1), grangerBC(rot1))
corrsrotated(2) = corr(grangerMCb(rot2), grangerMC2(rot2))
corrsrotated(3) = corr(grangerMCc(rot3), grangerDC(rot3))
corrsrotated(4) = corr(grangerBCb(rot4), grangerDCb(rot4))

clf
colors = [0 0 0; 1 0 0; 0 0 1];
colormap(colors);
subplot(2,2,1)
scatter(grangerMC, grangerBC, [], cc1)
xlabel('MC')
ylabel('BC')
title(['corr: ' num2str(corrs(1)) ' corr rotated: ' num2str(corrsrotated(1)) ' corr unrotated: ' num2str(corrsunrotated(1))])
subplot(2,2,2)
scatter(grangerMCb, grangerMC2, [], cc2)
xlabel('MC1')
ylabel('MC2')
title(['corr: ' num2str(corrs(2)) ' corr rotated: ' num2str(corrsrotated(2)) ' corr unrotated: ' num2str(corrsunrotated(2))])
subplot(2,2,3)
scatter(grangerMCc, grangerDC, [], cc3)
xlabel('MC')
ylabel('DC')
title(['corr: ' num2str(corrs(3)) ' corr rotated: ' num2str(corrsrotated(3)) ' corr unrotated: ' num2str(corrsunrotated(3))])
subplot(2,2,4)
scatter(grangerBCb, grangerDCb, [], cc4)
xlabel('BC')
ylabel('DC')
title(['corr: ' num2str(corrs(4)) ' corr rotated: ' num2str(corrsrotated(4)) ' corr unrotated: ' num2str(corrsunrotated(4))])
saveplot(gcf, './worksheets/2015_11_03-bcireportplots/grangercondcompareFromBCunits.eps')


