conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%For individual recordings
bcrec = fetch(exec(conn, ['SELECT et.`1DBCrecording` FROM experiment_tuning et']));
bcrec = bcrec.Data;
nR = size(bcrec,1);

means = [];

for idx = 1:nR
	idx
	bcfile = bcrec{idx,1};
	%TP<-TP
	grangerBCTPTP = fetch(exec(conn, ['SELECT fBC.unit tounit, '...
	' egBC.fromunit, egBC.score egBCscore, flinT.dev, flinTV.dev, flinC.dev, flinCV.dev, flin_fromT.dev, flin_fromTV.dev, flin_fromC.dev, flin_fromCV.dev FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fBC '...
	'ON et.`1DBCrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `fits` flinT '...
	'ON flinT.`nev file` = fBC.`nev file` AND flinT.unit = fBC.unit '...
	'INNER JOIN `fits` flinTV '...
	'ON flinTV.`nev file` = fBC.`nev file` AND flinTV.unit = fBC.unit '...
	'INNER JOIN `fits` flinC '...
	'ON flinC.`nev file` = fBC.`nev file` AND flinC.unit = fBC.unit '...
	'INNER JOIN `fits` flinCV '...
	'ON flinCV.`nev file` = fBC.`nev file` AND flinCV.unit = fBC.unit '...
	'INNER JOIN `fits` flin_fromT '...
	'ON flin_fromT.`nev file` = fBC.`nev file` AND flin_fromT.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromTV '...
	'ON flin_fromTV.`nev file` = fBC.`nev file` AND flin_fromTV.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromC '...
	'ON flin_fromC.`nev file` = fBC.`nev file` AND flin_fromC.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromCV '...
	'ON flin_fromCV.`nev file` = fBC.`nev file` AND flin_fromCV.unit = egBC.fromunit '...
	'WHERE fBC.modelID = 29 AND flinT.modelID = 1 AND flinTV.modelID = 30 AND flinC.modelID = 7 AND flinCV.modelID = 28 AND flin_fromT.modelID = 1 AND flin_fromTV.modelID = 30 AND flin_fromC.modelID = 7 AND flin_fromCV.modelID = 28 AND fBC.`nev file` = "' bcfile '"'...
	' AND ((flinT.dev < flinCV.dev  AND flinT.dev < flinC.dev) OR (flinTV.dev < flinC.dev AND flinTV.dev < flinCV.dev)) '...
	' AND ((flin_fromT.dev < flin_fromCV.dev  AND flin_fromT.dev < flin_fromC.dev) OR (flin_fromTV.dev < flin_fromC.dev AND flin_fromTV.dev < flin_fromCV.dev))']));
	if ~strcmp(grangerBCTPTP.Data{1}, 'No Data')
		grangerBCTPTP = cell2mat(grangerBCTPTP.Data(:,3));
		above20(idx,1) = sum(grangerBCTPTP > 20)/length(grangerBCTPTP);
		means(idx,1) = mean(grangerBCTPTP);
	end

	%TP<-CP
	grangerBCTPCP = fetch(exec(conn, ['SELECT fBC.unit tounit, '...
	' egBC.fromunit, egBC.score egBCscore, flinT.dev, flinTV.dev, flinC.dev, flinCV.dev, flin_fromT.dev, flin_fromTV.dev, flin_fromC.dev, flin_fromCV.dev FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fBC '...
	'ON et.`1DBCrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `fits` flinT '...
	'ON flinT.`nev file` = fBC.`nev file` AND flinT.unit = fBC.unit '...
	'INNER JOIN `fits` flinTV '...
	'ON flinTV.`nev file` = fBC.`nev file` AND flinTV.unit = fBC.unit '...
	'INNER JOIN `fits` flinC '...
	'ON flinC.`nev file` = fBC.`nev file` AND flinC.unit = fBC.unit '...
	'INNER JOIN `fits` flinCV '...
	'ON flinCV.`nev file` = fBC.`nev file` AND flinCV.unit = fBC.unit '...
	'INNER JOIN `fits` flin_fromT '...
	'ON flin_fromT.`nev file` = fBC.`nev file` AND flin_fromT.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromTV '...
	'ON flin_fromTV.`nev file` = fBC.`nev file` AND flin_fromTV.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromC '...
	'ON flin_fromC.`nev file` = fBC.`nev file` AND flin_fromC.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromCV '...
	'ON flin_fromCV.`nev file` = fBC.`nev file` AND flin_fromCV.unit = egBC.fromunit '...
	'WHERE fBC.modelID = 29 AND flinT.modelID = 1 AND flinTV.modelID = 30 AND flinC.modelID = 7 AND flinCV.modelID = 28 AND flin_fromT.modelID = 1 AND flin_fromTV.modelID = 30 AND flin_fromC.modelID = 7 AND flin_fromCV.modelID = 28 AND fBC.`nev file` = "' bcfile '"'...
	' AND ((flinT.dev < flinCV.dev  AND flinT.dev < flinC.dev) OR (flinTV.dev < flinC.dev AND flinTV.dev < flinCV.dev)) '...
	' AND ((flin_fromC.dev < flin_fromTV.dev  AND flin_fromC.dev < flin_fromT.dev) OR (flin_fromCV.dev < flin_fromT.dev AND flin_fromCV.dev < flin_fromTV.dev))']));
	if ~strcmp(grangerBCTPCP.Data{1}, 'No Data')
		grangerBCTPCP = cell2mat(grangerBCTPCP.Data(:,3));
		above20(idx,2) = sum(grangerBCTPCP > 20)/length(grangerBCTPCP);
		means(idx,2) = mean(grangerBCTPCP);
	end

	%CP<-TP
	grangerBCCPTP = fetch(exec(conn, ['SELECT fBC.unit tounit, '...
	' egBC.fromunit, egBC.score egBCscore, flinT.dev, flinTV.dev, flinC.dev, flinCV.dev, flin_fromT.dev, flin_fromTV.dev, flin_fromC.dev, flin_fromCV.dev FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fBC '...
	'ON et.`1DBCrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `fits` flinT '...
	'ON flinT.`nev file` = fBC.`nev file` AND flinT.unit = fBC.unit '...
	'INNER JOIN `fits` flinTV '...
	'ON flinTV.`nev file` = fBC.`nev file` AND flinTV.unit = fBC.unit '...
	'INNER JOIN `fits` flinC '...
	'ON flinC.`nev file` = fBC.`nev file` AND flinC.unit = fBC.unit '...
	'INNER JOIN `fits` flinCV '...
	'ON flinCV.`nev file` = fBC.`nev file` AND flinCV.unit = fBC.unit '...
	'INNER JOIN `fits` flin_fromT '...
	'ON flin_fromT.`nev file` = fBC.`nev file` AND flin_fromT.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromTV '...
	'ON flin_fromTV.`nev file` = fBC.`nev file` AND flin_fromTV.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromC '...
	'ON flin_fromC.`nev file` = fBC.`nev file` AND flin_fromC.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromCV '...
	'ON flin_fromCV.`nev file` = fBC.`nev file` AND flin_fromCV.unit = egBC.fromunit '...
	'WHERE fBC.modelID = 29 AND flinT.modelID = 1 AND flinTV.modelID = 30 AND flinC.modelID = 7 AND flinCV.modelID = 28 AND flin_fromT.modelID = 1 AND flin_fromTV.modelID = 30 AND flin_fromC.modelID = 7 AND flin_fromCV.modelID = 28 AND fBC.`nev file` = "' bcfile '"'...
	' AND ((flin_fromT.dev < flin_fromCV.dev  AND flin_fromT.dev < flin_fromC.dev) OR (flin_fromTV.dev < flin_fromC.dev AND flin_fromTV.dev < flin_fromCV.dev)) '...
	' AND ((flinC.dev < flinTV.dev  AND flinC.dev < flinT.dev) OR (flinCV.dev < flinT.dev AND flinCV.dev < flinTV.dev))']));
	if ~strcmp(grangerBCCPTP.Data{1}, 'No Data')
		grangerBCCPTP = cell2mat(grangerBCCPTP.Data(:,3));
		above20(idx,3) = sum(grangerBCCPTP > 20)/length(grangerBCCPTP);
		means(idx,3) = mean(grangerBCCPTP);
	end

	%CP<-CP
	grangerBCCPCP = fetch(exec(conn, ['SELECT fBC.unit tounit, '...
	' egBC.fromunit, egBC.score egBCscore, flinT.dev, flinTV.dev, flinC.dev, flinCV.dev, flin_fromT.dev, flin_fromTV.dev, flin_fromC.dev, flin_fromCV.dev FROM `experiment_tuning` et '...
	'INNER JOIN `fits` fBC '...
	'ON et.`1DBCrecording` = fBC.`nev file` '...
	'INNER JOIN `estimates_granger` egBC '...
	'ON egBC.`id` = fBC.`id` '...
	'INNER JOIN `fits` flinT '...
	'ON flinT.`nev file` = fBC.`nev file` AND flinT.unit = fBC.unit '...
	'INNER JOIN `fits` flinTV '...
	'ON flinTV.`nev file` = fBC.`nev file` AND flinTV.unit = fBC.unit '...
	'INNER JOIN `fits` flinC '...
	'ON flinC.`nev file` = fBC.`nev file` AND flinC.unit = fBC.unit '...
	'INNER JOIN `fits` flinCV '...
	'ON flinCV.`nev file` = fBC.`nev file` AND flinCV.unit = fBC.unit '...
	'INNER JOIN `fits` flin_fromT '...
	'ON flin_fromT.`nev file` = fBC.`nev file` AND flin_fromT.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromTV '...
	'ON flin_fromTV.`nev file` = fBC.`nev file` AND flin_fromTV.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromC '...
	'ON flin_fromC.`nev file` = fBC.`nev file` AND flin_fromC.unit = egBC.fromunit '...
	'INNER JOIN `fits` flin_fromCV '...
	'ON flin_fromCV.`nev file` = fBC.`nev file` AND flin_fromCV.unit = egBC.fromunit '...
	'WHERE fBC.modelID = 29 AND flinT.modelID = 1 AND flinTV.modelID = 30 AND flinC.modelID = 7 AND flinCV.modelID = 28 AND flin_fromT.modelID = 1 AND flin_fromTV.modelID = 30 AND flin_fromC.modelID = 7 AND flin_fromCV.modelID = 28 AND fBC.`nev file` = "' bcfile '"'...
	' AND ((flinC.dev < flinTV.dev  AND flinC.dev < flinT.dev) OR (flinCV.dev < flinT.dev AND flinCV.dev < flinTV.dev)) '...
	' AND ((flin_fromC.dev < flin_fromTV.dev  AND flin_fromC.dev < flin_fromT.dev) OR (flin_fromCV.dev < flin_fromT.dev AND flin_fromCV.dev < flin_fromTV.dev))']));
	if ~strcmp(grangerBCCPCP.Data{1}, 'No Data')
		grangerBCCPCP = cell2mat(grangerBCCPCP.Data(:,3));
		above20(idx,4) = sum(grangerBCCPCP > 20)/length(grangerBCCPCP);
		means(idx,4) = mean(grangerBCCPCP);
	end
end

mean(means)
%Doesn't show much...

%Shows cursor preferring connections are more significant...
ii=any(above20==0,2);
mean(above20(~ii,:))
%Not sure this is enough data to conclude anything though...