conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%%%%%%%%%%%%%
%To BC units%
%%%%%%%%%%%%%

grangerMCBC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`1DBCrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`1DBCrecording` AND bci.unit = fMC.unit)']));
grangerMC = cell2mat(grangerMCBC.Data(:,5));
grangerBC = cell2mat(grangerMCBC.Data(:,6));
tuningtype = cell2mat(grangerMCBC.Data(:,9));
cc1 = ones(size(tuningtype));
cc1(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc1(tuningtype == 5) = 3;

devconstMC = cell2mat(grangerMCBC.Data(:,7));
devconstBC = cell2mat(grangerMCBC.Data(:,8));
normgrangerMC = 100*grangerMC./devconstMC;
normgrangerBC = 100*grangerBC./devconstBC;

unrot1 = tuningtype == 5;
rot1 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned1 = tuningtype == 4;

grangerMCBCall = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`1DBCrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31']));
grangerMCall = cell2mat(grangerMCBCall.Data(:,5));
grangerBCall = cell2mat(grangerMCBCall.Data(:,6));
tuningtypeall = cell2mat(grangerMCBCall.Data(:,9));
cc1all = ones(size(tuningtypeall));
cc1all(tuningtypeall == 1 | tuningtypeall == 3 | tuningtypeall == 4) = 2;
cc1all(tuningtypeall == 5) = 3;

devconstMCall = cell2mat(grangerMCBCall.Data(:,7));
devconstBCall = cell2mat(grangerMCBCall.Data(:,8));
normgrangerMCall = 100*grangerMCall./devconstMCall;
normgrangerBCall = 100*grangerBCall./devconstBCall;

clf
histogram(normgrangerBC-normgrangerMC, 'Normalization', 'probability')               
hold on; histogram(normgrangerBCall-normgrangerMCall, 'Normalization', 'probability')
legend('to BC units', 'to all units')

saveplot(gcf, './worksheets/2016_06_10-resultsforpaper/grangerMCBCcompareToBCunits.eps', 'eps', [10 10])

grangerMCDC = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`1DBCrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id'...
' AND fconstBC.modelID = 31 AND fconstMC.modelID = 31 '...
'AND EXISTS (SELECT * FROM `bci_units` bci WHERE bci.`ID` = et.`dualrecording` AND bci.unit = fMC.unit)']));
grangerMCc = cell2mat(grangerMCDC.Data(:,5));
grangerDC = cell2mat(grangerMCDC.Data(:,6));
tuningtype = cell2mat(grangerMCDC.Data(:,9));
cc3 = ones(size(tuningtype));
cc3(tuningtype == 1 | tuningtype == 3 | tuningtype == 4) = 2;
cc3(tuningtype == 5) = 3;

devconstMCc = cell2mat(grangerMCDC.Data(:,7));
devconstDC = cell2mat(grangerMCDC.Data(:,8));
normgrangerMC = 100*grangerMCc./devconstMCc;
normgrangerDC = 100*grangerDC./devconstDC;

unrot3 = tuningtype == 5;
rot3 = (tuningtype == 1 | tuningtype == 3| tuningtype == 4);
untuned3 = tuningtype == 4;

grangerMCDCall = fetch(exec(conn, ['SELECT fBC.analyses_id, fMC.`nev file`, fMC.unit tounit, '...
' egMC.fromunit, egMC.score egMCscore, egBC.score egBCscore, fconstMC.dev, fconstBC.dev, et.`tuning_type` FROM `experiment_tuning` et '...
'INNER JOIN `fits` fMC '...
'ON et.`manualrecording` = fMC.`nev file` '...
'INNER JOIN `estimates_granger` egMC '...
'ON egMC.`id` = fMC.`id` '...
'INNER JOIN `fits` fBC '...
'ON et.`dualrecording` = fBC.`nev file` '...
'INNER JOIN `estimates_granger` egBC '...
'ON egBC.`id` = fBC.`id` '...
'INNER JOIN `fits` fconstBC '...
'ON fconstBC.`nev file` = et.`dualrecording` AND fconstBC.unit = fMC.unit '...
'INNER JOIN `fits` fconstMC '...
'ON fconstMC.`nev file` = et.`manualrecording` AND fconstMC.unit = fMC.unit '...
'WHERE fMC.unit = fBC.unit AND egMC.fromunit = egBC.fromunit AND fMC.modelID = 29 AND fBC.modelID = 29 AND fMC.analyses_id = fBC.analyses_id '...
'AND fconstBC.modelID = 31 AND fconstMC.modelID = 31']));
grangerMCall = cell2mat(grangerMCDCall.Data(:,5));
grangerDCall = cell2mat(grangerMCDCall.Data(:,6));
tuningtypeall = cell2mat(grangerMCDCall.Data(:,9));
cc1all = ones(size(tuningtypeall));
cc1all(tuningtypeall == 1 | tuningtypeall == 3 | tuningtypeall == 4) = 2;
cc1all(tuningtypeall == 5) = 3;

devconstMCall = cell2mat(grangerMCDCall.Data(:,7));
devconstDCall = cell2mat(grangerMCDCall.Data(:,8));
normgrangerMCall = 100*grangerMCall./devconstMCall;
normgrangerDCall = 100*grangerDCall./devconstDCall;

clf
histogram(normgrangerDC-normgrangerMC, 'Normalization', 'probability')               
hold on; histogram(normgrangerDCall-normgrangerMCall, 'Normalization', 'probability')
legend('to BC units', 'to all units')
saveplot(gcf, './worksheets/2016_06_10-resultsforpaper/grangerMCDCcompareToBCunits.eps', 'eps', [10 10])
