conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
data = fetch(exec(conn, ['SELECT fgc.`nev file`, eg.fromunit, eg.score, SUM(ep.value)'...
' FROM fits fgc'...
' INNER JOIN estimates_granger eg '...
' ON fgc.id = eg.id'...
' INNER JOIN fits fglm'... 
' ON fgc.`nev file` = fglm.`nev file` AND fglm.unit = fgc.unit '...
' INNER JOIN estimates_parameters ep '...
' ON ep.id = fglm.id AND concat(''spike unit'', eg.fromnum) = ep.label'...
' WHERE fgc.modelID = 2 AND fglm.modelID = 24'...
' GROUP BY fgc.`nev file`, eg.fromunit, fgc.unit']));

data = cell2mat(data.Data(:,3:4));
%Chop off large values...
ii_lg = abs(data(:,1))>1e3 | abs(data(:,2))>1e3;
data = data(~ii_lg,:);
plot(data(:,1), data(:,2), '.'); xlabel('GC'); ylabel('Sum filters'); ylim([-10 10]); xlim([0 100])

smoothhist2D(data, 5, [1000, 1000]); axis xy; xlim([0 60]); ylim([-5 5]); xlabel('GC'); ylabel('\Sigma k_i')  
hold on; plot([0 60], [0 0], 'r') 
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/gc_sum_network_filters.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
absdata = fetch(exec(conn, ['SELECT fgc.`nev file`, eg.fromunit, eg.score, SUM(ABS(ep.value))'...
' FROM fits fgc'...
' INNER JOIN estimates_granger eg '...
' ON fgc.id = eg.id'...
' INNER JOIN fits fglm'... 
' ON fgc.`nev file` = fglm.`nev file` AND fglm.unit = fgc.unit '...
' INNER JOIN estimates_parameters ep '...
' ON ep.id = fglm.id AND concat(''spike unit'', eg.fromnum) = ep.label'...
' WHERE fgc.modelID = 2 AND fglm.modelID = 24'...
' GROUP BY fgc.`nev file`, eg.fromunit, fgc.unit']));

absdata = cell2mat(absdata.Data(:,3:4));
%Chop off large values...
ii_lg = abs(absdata(:,1))>1e3 | abs(absdata(:,2))>1e3;
absdata = absdata(~ii_lg,:);
plot(absdata(:,1), absdata(:,2), '.', [0 100], [0 0], 'r'); xlabel('GC'); ylabel('\Sigma |k_i|'); ylim([-10 10]); xlim([0 100])

figure
smoothhist2D(absdata, 5, [1000, 1000]); axis xy; xlim([0 60]); ylim([0 5]); xlabel('GC'); ylabel('\Sigma |k_i|')  
hold on; plot([0 60], [0 0], 'r') 




20130920SpankyUtah004.nev
from 55.1 to 31.1 sum(abs(filters)) = .18137 (fit id 193326), GC score = 124.226