%Compare in-degree of BCI units with in-degree of non-BCI units
conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Granger scores, contra-contra connections
BCIin = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' INNER JOIN bci_units bci '...
' ON bci.id = f.`nev file` AND f.unit = bci.unit'...
' WHERE f.modelID = 2'...
' GROUP BY f.`nev file`,f.unit']))
BCIin = cell2mat(BCIin.Data);

nonBCIin = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2 AND NOT EXISTS (SELECT * FROM bci_units bci WHERE bci.id = f.id AND f.unit = bci.unit)'...
' GROUP BY f.`nev file`,f.unit']))
nonBCIin = cell2mat(nonBCIin.Data);

figure
[fBCIin,xiBCIin] = ksdensity((BCIin), 'width', .8, 'npoints', 600);
[fnBCIin,xinBCIin] = ksdensity((nonBCIin), 'width', .8, 'npoints', 600);
plot(xiBCIin,fBCIin, xinBCIin,fnBCIin);
xlabel('GC')
ylabel('Density')
xlim([1 50])
legend('BCI', 'non BCI')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC-indegree_bci_nonbci.eps')


BCIout = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' INNER JOIN bci_units bci '...
' ON bci.id = f.`nev file` AND eg.fromunit = bci.unit'...
' WHERE f.modelID = 2'...
' GROUP BY f.`nev file`,eg.fromunit']))
BCIout = cell2mat(BCIout.Data);

nonBCIout = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2 AND NOT EXISTS (SELECT * FROM bci_units bci WHERE bci.id = f.id AND eg.fromunit = bci.unit)'...
' GROUP BY f.`nev file`,eg.fromunit']))
nonBCIout = cell2mat(nonBCIout.Data);

figure
[fBCIout,xiBCIout] = ksdensity((BCIout), 'width', .8, 'npoints', 600);
[fnBCIout,xinBCIout] = ksdensity((nonBCIout), 'width', .8, 'npoints', 600);
plot(xiBCIout,fBCIout, xinBCIout,fnBCIout);
xlabel('GC')
ylabel('Density')
xlim([1 50])
legend('BCI', 'non BCI')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC-outdegree_bci_nonbci.eps')

%Normalize by firing rate, too