%Compute sum of granger scores for out degree for given unit and nev file
conn = database('','root','Fairbanks1!','com.mysql.jdbc.Driver', ...
	'jdbc:mysql://fairbanks.amath.washington.edu:3306/spanky_db');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Granger scores, contra-contra connections
CCdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit < 97']))
%' INNER JOIN experiment_tuning et '...
%' ON f.`nev file` = et.`manualrecording` '...
CCdata = cell2mat(CCdata.Data);

CIdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' WHERE f.modelID = 2 AND f.unit > 96 AND eg.fromunit < 97']))
%' INNER JOIN experiment_tuning et '...
%' ON f.`nev file` = et.`manualrecording` '...
CIdata = cell2mat(CIdata.Data);

ICdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit > 96']))
%' INNER JOIN experiment_tuning et '...
%' ON f.`nev file` = et.`manualrecording` '...
ICdata = cell2mat(ICdata.Data);

IIdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' WHERE f.modelID = 2 AND f.unit > 96 AND eg.fromunit > 96']))
%' INNER JOIN experiment_tuning et '...
%' ON f.`nev file` = et.`manualrecording` '...
IIdata = cell2mat(IIdata.Data);

figure
[fCC,xiCC] = ksdensity((CCdata), 'width', 2, 'npoints', 600);
[fCI,xiCI] = ksdensity((CIdata), 'width', 2, 'npoints', 600);
[fIC,xiIC] = ksdensity((ICdata), 'width', 2, 'npoints', 600);
[fII,xiII] = ksdensity((IIdata), 'width', 2, 'npoints', 600);
plot(xiCC,fCC, xiCI,fCI, xiIC,fIC, xiII,fII);
title('All data')
xlabel('GC')
ylabel('Density')
xlim([1 50])
legend('Contra->contra', 'Contra->Ipsi', 'Ipsi->Contra', 'Ipsi->Ipsi')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC_hemispheres.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CCdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit < 97']))
CCdata = cell2mat(CCdata.Data);

CIdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2 AND f.unit > 96 AND eg.fromunit < 97']))
CIdata = cell2mat(CIdata.Data);

ICdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit > 96']))
ICdata = cell2mat(ICdata.Data);

IIdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2 AND f.unit > 96 AND eg.fromunit > 96']))
IIdata = cell2mat(IIdata.Data);



figure
[fCC,xiCC] = ksdensity((CCdata), 'width', 2, 'npoints', 600);
[fCI,xiCI] = ksdensity((CIdata), 'width', 2, 'npoints', 600);
[fIC,xiIC] = ksdensity((ICdata), 'width', 2, 'npoints', 600);
[fII,xiII] = ksdensity((IIdata), 'width', 2, 'npoints', 600);
plot(xiCC,fCC, xiCI,fCI, xiIC,fIC, xiII,fII);
title('Manual control')
xlabel('GC')
ylabel('Density')
xlim([1 50])
legend('Contra->contra', 'Contra->Ipsi', 'Ipsi->Contra', 'Ipsi->Ipsi')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC_hemispheres_MC.eps')



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

CCdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit < 97']))
CCdata = cell2mat(CCdata.Data);

CIdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2 AND f.unit > 96 AND eg.fromunit < 97']))
CIdata = cell2mat(CIdata.Data);

ICdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit > 96']))
ICdata = cell2mat(ICdata.Data);

IIdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2 AND f.unit > 96 AND eg.fromunit > 96']))
IIdata = cell2mat(IIdata.Data);



figure
[fCC,xiCC] = ksdensity((CCdata), 'width', 2, 'npoints', 600);
[fCI,xiCI] = ksdensity((CIdata), 'width', 2, 'npoints', 600);
[fIC,xiIC] = ksdensity((ICdata), 'width', 2, 'npoints', 600);
[fII,xiII] = ksdensity((IIdata), 'width', 2, 'npoints', 600);
plot(xiCC,fCC, xiCI,fCI, xiIC,fIC, xiII,fII);
title('Brain control')
xlabel('GC')
ylabel('Density')
xlim([1 50])
legend('Contra->contra', 'Contra->Ipsi', 'Ipsi->Contra', 'Ipsi->Ipsi')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC_hemispheres_BC.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Compare brain and manual control 

BCdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording`'...
' WHERE f.modelID = 2']))
BCdata = cell2mat(BCdata.Data);

MCdata = fetch(exec(conn, ['SELECT eg.score FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2']))
MCdata = cell2mat(MCdata.Data);

figure
[fMC,xiMC] = ksdensity((MCdata), 'width', 2, 'npoints', 600);
[fBC,xiBC] = ksdensity((BCdata), 'width', 2, 'npoints', 600);
plot(xiBC,fBC, xiMC,fMC);
xlim([0 50])
legend('Brain control', 'Manual control')
xlabel('GC')
ylabel('Density')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC_MC_BC.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Average by node to get mean in-degree of network

BCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording`'...
' WHERE f.modelID = 2'...
' GROUP BY f.unit, f.`nev file`']))
BCdata = cell2mat(BCdata.Data);

MCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2'...
' GROUP BY f.unit, f.`nev file`']))
MCdata = cell2mat(MCdata.Data);

figure
[fMC,xiMC] = ksdensity((MCdata), 'width', 1, 'npoints', 500);
[fBC,xiBC] = ksdensity((BCdata), 'width', 1, 'npoints', 500);
plot(xiBC,fBC,xiMC,fMC);
xlim([3 50])
legend('Brain control', 'Manual control')
title('Mean in-degree')
xlabel('GC')
ylabel('Density')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GCin-degree_MC_BC.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Average by node to get mean out-degree of network

BCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording`'...
' WHERE f.modelID = 2'...
' GROUP BY eg.fromunit, f.`nev file`']))
BCdata = cell2mat(BCdata.Data);

MCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2'...
' GROUP BY eg.fromunit, f.`nev file`']))
MCdata = cell2mat(MCdata.Data);

figure
[fMC,xiMC] = ksdensity((MCdata), 'width', 1, 'npoints', 500);
[fBC,xiBC] = ksdensity((BCdata), 'width', 1, 'npoints', 500);
plot(xiBC,fBC,xiMC,fMC);
xlim([3 50])
legend('Brain control', 'Manual control')
title('Mean out-degree')
xlabel('GC')
ylabel('Density')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GCout-degree_MC_BC.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Mean in-degree vs mean out-degree (all)

INdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' WHERE f.modelID = 2'...
' GROUP BY f.unit, f.`nev file`']))
INdata = cell2mat(INdata.Data);

OUTdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' WHERE f.modelID = 2'...
' GROUP BY eg.fromunit, f.`nev file`']))
OUTdata = cell2mat(OUTdata.Data);

figure
[fOUT,xiOUT] = ksdensity((OUTdata), 'width', 1, 'npoints', 500);
[fIN,xiIN] = ksdensity((INdata), 'width', 1, 'npoints', 500);
plot(xiIN,fIN, xiOUT,fOUT);
legend('in-degree', 'out-degree')
xlim([3 50])
xlabel('GC')
title('All data')
ylabel('Density')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GCin-out-degree.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Mean in-degree vs mean out-degree (MC)
INMCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2'...
' GROUP BY f.unit, f.`nev file`']))
INMCdata = cell2mat(INMCdata.Data);

OUTMCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`manualrecording` '...
' WHERE f.modelID = 2'...
' GROUP BY eg.fromunit, f.`nev file`']))
OUTMCdata = cell2mat(OUTMCdata.Data);

figure
[fOUTMC,xiOUTMC] = ksdensity((OUTMCdata), 'width', 1, 'npoints', 500);
[fINMC,xiINMC] = ksdensity((INMCdata), 'width', 1, 'npoints', 500);
plot(xiINMC,fINMC, xiOUTMC,fOUTMC);
legend('in-degree', 'out-degree')
xlim([3 50])
xlabel('GC')
title('Manual control')
ylabel('Density')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GCin-out-degree_MC.eps')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Mean in-degree vs mean out-degree (BC)
INBCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2'...
' GROUP BY f.unit, f.`nev file`']))
INBCdata = cell2mat(INBCdata.Data);

OUTBCdata = fetch(exec(conn, ['SELECT AVG(eg.score) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN experiment_tuning et '...
' ON f.`nev file` = et.`1DBCrecording` '...
' WHERE f.modelID = 2'...
' GROUP BY eg.fromunit, f.`nev file`']))
OUTBCdata = cell2mat(OUTBCdata.Data);

figure
[fOUTBC,xiOUTBC] = ksdensity((OUTBCdata), 'width', 1, 'npoints', 500);
[fINBC,xiINBC] = ksdensity((INBCdata), 'width', 1, 'npoints', 500);
plot(xiINBC,fINBC, xiOUTBC,fOUTBC);
legend('in-degree', 'out-degree')
xlim([3 50])
xlabel('GC')
title('Brain control')
ylabel('Density')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GCin-out-degree_BC.eps')


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%How is granger related to firing rate of neuron
GCdata = fetch(exec(conn, ['SELECT AVG(eg.score), AVG(u.firingrate) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN units u'...
' ON u.`nev file` = f.`nev file` AND u.unit = f.unit'...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit < 97'...
' GROUP BY f.`nev file`,f.unit']))

GCdata = cell2mat(GCdata.Data);
smoothhist2D(fliplr(GCdata), 6, [500, 500]); axis xy; xlim([0 60]); ylim([0 45]);
ylabel('GC score')
xlabel('Firing rate')
title('Average in-degree GC')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC-firingrate-in.eps')


GCdata = fetch(exec(conn, ['SELECT AVG(eg.score), AVG(u.firingrate) FROM `fits` f '...
' INNER JOIN estimates_granger eg '...
' ON eg.id = f.id '...
' INNER JOIN units u'...
' ON u.`nev file` = f.`nev file` AND u.unit = eg.fromunit'...
' WHERE f.modelID = 2 AND f.unit < 97 AND eg.fromunit < 97'...
' GROUP BY f.`nev file`,eg.fromunit']))

GCdata = cell2mat(GCdata.Data);
smoothhist2D(fliplr(GCdata), 6, [500, 500]); axis xy; xlim([0 60]); ylim([0 45]);
ylabel('GC score')
xlabel('Firing rate')
title('Average out-degree GC')
saveplot(gcf, './worksheets/2015_08_23-BasicGrangerAnalysis/GC-firingrate-out.eps')
